services:
  order-db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: orderdb
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_HOST: '%'
    ports:
      - "3308:3306"
    volumes:
      - order-db-data:/var/lib/mysql
    networks:
      - order-network
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      retries: 5
      start_period: 20s

  order-api:
    build: .
    ports:
      - "8083:8083"
    depends_on:
      order-db:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://order-db:3306/orderdb
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    networks:
      - order-network
      - msa-net # 카프카


networks:
  order-network:
    driver: bridge
  msa-net:
    external: true

volumes:
  order-db-data:
